version: '3.8'
services:
  elasticsearch-snlp:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    container_name: elasticsearch-snlp
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch-snlp/data
    ports:
      - 9200:9200
      - 9300:9300

  kibana-snlp:
    container_name: kibana-snlp
    image: docker.elastic.co/kibana/kibana:7.14.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch-snlp:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch-snlp

  wordnet:
    image: jacopofar/wordnet-as-a-service:latest
    container_name: wordnet
    ports:
      - 5679:5679

volumes:
  elasticsearch-data:
    driver: local